spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  data:
    rest:
      basePath: /datarest

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

management:
  endpoint:
    logfile:
      enabled: true
      access: unrestricted
      external-file: log/app.log
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  health:
    defaults:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor

logging:
#  level:
#    ROOT: ERROR
#  file:
#    name: application.log


