version: '3.9'

services:

  books-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32768:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/books_db
      - SPRING_DATASOURCE_USERNAME=post
      - SPRING_DATASOURCE_PASSWORD=gres
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - my_net_1
    restart: unless-stopped


  postgres-db:
    image: "postgres:13"
    ports:
      - "32769:5432"
    environment:
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=gres
      - POSTGRES_DB=books_db
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - my_net_1
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=login@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    ports:
      - "32770:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - my_net_1
    restart: unless-stopped


networks:
  my_net_1:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:

