server:
  port: 7776
#  port: 0

eureka:
  client:
    fetch-registry: true
spring:
  application:
    name: mail_processor

application:
  notification:
    name: notification_service
#    url: http://localhost:7777
  kafka-bootstrap-servers: localhost:9092
  kafka-group-id: processorConsumerGroup
  topic-request: request
  topic-response: response
  auth_service:
    name: auth_service

jwt:
  public.key: classpath:app.pub

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 30
    instances:
      getOrderCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25
      tokenSendCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25
      tokensSendCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25