server:
  port: 7773

eureka:
  client:
    fetch-registry: true

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #      port: 0
      database: productDB

mongock:
  runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  public.key: classpath:app.pub

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 30
    instances:
      getAllProductCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25
      getProductCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25
      createProductCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25
      updateProductCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25
      tokenSendCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 25