#resilience4j:
#  circuitbreaker:
#    configs:
#      default:

#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 50
#        permittedNumberOfCallsInHalfOpenState: 10
#        slowCallDurationThreshold: 4s
#        slowCallRateThreshold: 50
#        failureRateThreshold: 25
#        waitDurationInOpenState: 20s
#        minimumNumberOfCalls: 20

#    slidingWindowType: COUNT_BASED
#    slidingWindowSize: 10
#    permittedNumberOfCallsInHalfOpenState: 3
#    slowCallDurationThreshold: 4s
#    slowCallRateThreshold: 5
#    failureRateThreshold: 5
#    waitDurationInOpenState: 10s
#    minimumNumberOfCalls: 5
#    instances:
#      myCircuitBreaker:
#        register-health-indicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        waitDurationInOpenState: 4s
#        failureRateThreshold: 50
#        slowCallDurationThreshold: 2s
#        slowCallRateThreshold: 30



#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 50
#        permittedNumberOfCallsInHalfOpenState: 10
#        slowCallDurationThreshold: 4s
#        slowCallRateThreshold: 50
#        failureRateThreshold: 25
#        waitDurationInOpenState: 20s
#        minimumNumberOfCalls: 20

#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 3
#        slowCallDurationThreshold: 4s
#        slowCallRateThreshold: 5
#        failureRateThreshold: 5
#        waitDurationInOpenState: 10s
#        minimumNumberOfCalls: 5

#  rateLimiter:
#    configs:
#      default:
#        timeoutDuration: 5s
#        limitForPeriod: 3
#        limit-refresh-period: 1s


#    instances:
#      myRateLimiter:
#        timeout-duration: 0
#        limit-for-period: 3
#        limit-refresh-period: 5s

#        timeoutDuration: 5s
#        limitForPeriod: 2
#        limitRefreshPeriod: 5s

#resilience4j:
#  ratelimiter:
#    instances:
#      myRateLimiter:
#        limit-for-period: 2
#        limit-refresh-period: 1s
#        timeout-duration: 0

#  circuitbreaker:
#    instances:
#      myCircuitBreaker:
#        register-health-indicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        slowCallDurationThreshold: 2s
#        slowCallRateThreshold: 30
#        recordExceptions:
#         - io.github.resilience4j.ratelimiter.RequestNotPermitted
#
#        ignoreExceptions:
##          - io.github.resilience4j.ratelimiter.RequestNotPermitted
#         - ru.otus.hw.exceptions.RateLimiterException

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/books_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  data:
    rest:
      basePath: /datarest

  jpa:
    database: postgresql
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoint:
    logfile:
      enabled: true
      access: unrestricted
      external-file: log/app.log
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      show-details: always
  health:
    defaults:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor

logging:
#  level:
#    ROOT: ERROR
#  file:
#    name: application.log


