version: '3.9'

services:

  project-app:
    build:
      context: ../book_service
      dockerfile: Dockerfile
    ports:
      - "32768:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_HOST=localhost
      - SPRING_DATA_PORT=27017
      - SPRING_DATA_DATABASE=projectDB
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - my_net_1
    restart: unless-stopped


  mongodb:
    image: "mongo:4.2.12"
    ports:
      - "32769:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME= admin
      - MONGO_INITDB_ROOT_PASSWORD= password
      - MONGO_INITDB_DATABASE= projectDB
    volumes:
      - db-data:/var/lib/mongodb/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - my_net_1
    restart: unless-stopped

  mongo_express:
    image: "mongo-express:0.54.0"
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=projectDB
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - "32770:8081"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - my_net_1
    restart: unless-stopped


networks:
  my_net_1:
    driver: bridge

volumes:
  db-data:
  pgadmin-data:

