spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #      port: 0
      database: hw15DB

  shell:
    interactive:
      enabled: true

mongock:
  #  runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local